/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 Adventurer.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Adventurer({
  hairColor = "green",
  topColor = "pink",
  bottomColor = "brown",
  ...props
}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Adventurer.glb");
  const { actions } = useAnimations(animations, group);
  console.log("actions", actions);
  const [animation, setAnimation] = useState("CharacterArmature|Idle");

  useEffect(() => {
    actions[animation].reset().fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group
            name="Adventurer_Body"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Adventurer_Body_1"
              geometry={nodes.Adventurer_Body_1.geometry}
              material={materials.LightGreen}
              skeleton={nodes.Adventurer_Body_1.skeleton}
            >
              <meshStandardMaterial color={topColor} />
            </skinnedMesh>
            <skinnedMesh
              name="Adventurer_Body_2"
              geometry={nodes.Adventurer_Body_2.geometry}
              material={materials.Skin}
              skeleton={nodes.Adventurer_Body_2.skeleton}
            ></skinnedMesh>
            <skinnedMesh
              name="Adventurer_Body_3"
              geometry={nodes.Adventurer_Body_3.geometry}
              material={materials.Green}
              skeleton={nodes.Adventurer_Body_3.skeleton}
            ></skinnedMesh>
            <skinnedMesh
              name="Adventurer_Body_4"
              geometry={nodes.Adventurer_Body_4.geometry}
              material={materials.White}
              skeleton={nodes.Adventurer_Body_4.skeleton}
            ></skinnedMesh>
            <skinnedMesh
              name="Adventurer_Body_5"
              geometry={nodes.Adventurer_Body_5.geometry}
              material={materials.Brown2}
              skeleton={nodes.Adventurer_Body_5.skeleton}
            ></skinnedMesh>
            <skinnedMesh
              name="Adventurer_Body_6"
              geometry={nodes.Adventurer_Body_6.geometry}
              material={materials.Gold}
              skeleton={nodes.Adventurer_Body_6.skeleton}
            ></skinnedMesh>
          </group>
          <group
            name="Adventurer_Feet"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Adventurer_Feet_1"
              geometry={nodes.Adventurer_Feet_1.geometry}
              material={materials.Brown2}
              skeleton={nodes.Adventurer_Feet_1.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Feet_2"
              geometry={nodes.Adventurer_Feet_2.geometry}
              material={materials.Brown_02}
              skeleton={nodes.Adventurer_Feet_2.skeleton}
            />
          </group>
          <group
            name="Adventurer_Head"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Adventurer_Head_1"
              geometry={nodes.Adventurer_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Adventurer_Head_1.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Head_2"
              geometry={nodes.Adventurer_Head_2.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Adventurer_Head_2.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Head_3"
              geometry={nodes.Adventurer_Head_3.geometry}
              material={materials.Brown}
              skeleton={nodes.Adventurer_Head_3.skeleton}
            />
          </group>
          <group
            name="Adventurer_Legs"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Adventurer_Legs_1"
              geometry={nodes.Adventurer_Legs_1.geometry}
              material={materials.LightGreen}
              skeleton={nodes.Adventurer_Legs_1.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Legs_2"
              geometry={nodes.Adventurer_Legs_2.geometry}
              material={materials.Skin}
              skeleton={nodes.Adventurer_Legs_2.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Legs_3"
              geometry={nodes.Adventurer_Legs_3.geometry}
              material={materials.White}
              skeleton={nodes.Adventurer_Legs_3.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Legs_4"
              geometry={nodes.Adventurer_Legs_4.geometry}
              material={materials.Brown2}
              skeleton={nodes.Adventurer_Legs_4.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Legs_5"
              geometry={nodes.Adventurer_Legs_5.geometry}
              material={materials.Gold}
              skeleton={nodes.Adventurer_Legs_5.skeleton}
            />
            <skinnedMesh
              name="Adventurer_Legs_6"
              geometry={nodes.Adventurer_Legs_6.geometry}
              material={materials.Brown_02}
              skeleton={nodes.Adventurer_Legs_6.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Adventurer.glb");
