/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 Hooded Adventurer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function HoodedAdventurer(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Hooded Adventurer.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <group name="Medieval_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Medieval_Body_1" geometry={nodes.Medieval_Body_1.geometry} material={materials.Black} skeleton={nodes.Medieval_Body_1.skeleton} />
            <skinnedMesh name="Medieval_Body_2" geometry={nodes.Medieval_Body_2.geometry} material={materials.LightBrown} skeleton={nodes.Medieval_Body_2.skeleton} />
            <skinnedMesh name="Medieval_Body_3" geometry={nodes.Medieval_Body_3.geometry} material={materials.DarkBrown} skeleton={nodes.Medieval_Body_3.skeleton} />
            <skinnedMesh name="Medieval_Body_4" geometry={nodes.Medieval_Body_4.geometry} material={materials.Skin} skeleton={nodes.Medieval_Body_4.skeleton} />
            <skinnedMesh name="Medieval_Body_5" geometry={nodes.Medieval_Body_5.geometry} material={materials.Gold} skeleton={nodes.Medieval_Body_5.skeleton} />
            <skinnedMesh name="Medieval_Body_6" geometry={nodes.Medieval_Body_6.geometry} material={materials.Metal} skeleton={nodes.Medieval_Body_6.skeleton} />
          </group>
          <group name="Medieval_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Medieval_Feet_1" geometry={nodes.Medieval_Feet_1.geometry} material={materials.LightBrown} skeleton={nodes.Medieval_Feet_1.skeleton} />
            <skinnedMesh name="Medieval_Feet_2" geometry={nodes.Medieval_Feet_2.geometry} material={materials.DarkBrown} skeleton={nodes.Medieval_Feet_2.skeleton} />
          </group>
          <group name="Medieval_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Medieval_Head_1" geometry={nodes.Medieval_Head_1.geometry} material={materials.Black} skeleton={nodes.Medieval_Head_1.skeleton} />
            <skinnedMesh name="Medieval_Head_2" geometry={nodes.Medieval_Head_2.geometry} material={materials.DarkBrown} skeleton={nodes.Medieval_Head_2.skeleton} />
            <skinnedMesh name="Medieval_Head_3" geometry={nodes.Medieval_Head_3.geometry} material={materials.Skin} skeleton={nodes.Medieval_Head_3.skeleton} />
            <skinnedMesh name="Medieval_Head_4" geometry={nodes.Medieval_Head_4.geometry} material={materials.White} skeleton={nodes.Medieval_Head_4.skeleton} />
            <skinnedMesh name="Medieval_Head_5" geometry={nodes.Medieval_Head_5.geometry} material={materials.Brown} skeleton={nodes.Medieval_Head_5.skeleton} />
          </group>
          <skinnedMesh name="Medieval_Legs" geometry={nodes.Medieval_Legs.geometry} material={materials.Black} skeleton={nodes.Medieval_Legs.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hooded Adventurer.glb')
