/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 Sci Fi Character.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function ScifiCharacter(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/Sci Fi Character.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group name="SciFi_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="SciFi_Body_1"
              geometry={nodes.SciFi_Body_1.geometry}
              material={materials.Black}
              skeleton={nodes.SciFi_Body_1.skeleton}
            />
            <skinnedMesh
              name="SciFi_Body_2"
              geometry={nodes.SciFi_Body_2.geometry}
              material={materials.LightBlue}
              skeleton={nodes.SciFi_Body_2.skeleton}
            />
            <skinnedMesh
              name="SciFi_Body_3"
              geometry={nodes.SciFi_Body_3.geometry}
              material={materials.Skin}
              skeleton={nodes.SciFi_Body_3.skeleton}
            />
            <skinnedMesh
              name="SciFi_Body_4"
              geometry={nodes.SciFi_Body_4.geometry}
              material={materials.Metal}
              skeleton={nodes.SciFi_Body_4.skeleton}
            />
            <skinnedMesh
              name="SciFi_Body_5"
              geometry={nodes.SciFi_Body_5.geometry}
              material={materials.Blue}
              skeleton={nodes.SciFi_Body_5.skeleton}
            />
          </group>
          <group name="SciFi_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="SciFi_Feet_1"
              geometry={nodes.SciFi_Feet_1.geometry}
              material={materials.Black}
              skeleton={nodes.SciFi_Feet_1.skeleton}
            />
            <skinnedMesh
              name="SciFi_Feet_2"
              geometry={nodes.SciFi_Feet_2.geometry}
              material={materials.Metal}
              skeleton={nodes.SciFi_Feet_2.skeleton}
            />
          </group>
          <group name="SciFi_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="SciFi_Head_1"
              geometry={nodes.SciFi_Head_1.geometry}
              material={materials.Black}
              skeleton={nodes.SciFi_Head_1.skeleton}
            />
            <skinnedMesh
              name="SciFi_Head_2"
              geometry={nodes.SciFi_Head_2.geometry}
              material={materials.Skin}
              skeleton={nodes.SciFi_Head_2.skeleton}
            />
            <skinnedMesh
              name="SciFi_Head_3"
              geometry={nodes.SciFi_Head_3.geometry}
              material={materials.Blue}
              skeleton={nodes.SciFi_Head_3.skeleton}
            />
            <skinnedMesh
              name="SciFi_Head_4"
              geometry={nodes.SciFi_Head_4.geometry}
              material={materials.Hair_Black}
              skeleton={nodes.SciFi_Head_4.skeleton}
            />
            <skinnedMesh
              name="SciFi_Head_5"
              geometry={nodes.SciFi_Head_5.geometry}
              material={materials.Brown}
              skeleton={nodes.SciFi_Head_5.skeleton}
            />
          </group>
          <group name="SciFi_Legs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="SciFi_Legs_1"
              geometry={nodes.SciFi_Legs_1.geometry}
              material={materials.Black}
              skeleton={nodes.SciFi_Legs_1.skeleton}
            />
            <skinnedMesh
              name="SciFi_Legs_2"
              geometry={nodes.SciFi_Legs_2.geometry}
              material={materials.LightBlue}
              skeleton={nodes.SciFi_Legs_2.skeleton}
            />
            <skinnedMesh
              name="SciFi_Legs_3"
              geometry={nodes.SciFi_Legs_3.geometry}
              material={materials.Metal}
              skeleton={nodes.SciFi_Legs_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Sci Fi Character.glb");
